export const LibraAbi = [
  {
    inputs: [
      { internalType: "address", name: "initialOwner", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "InvalidSignature", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "orderId",
        type: "string",
      },
    ],
    name: "EventCancelOrder",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "orderId",
        type: "string",
      },
    ],
    name: "EventConfirmDeliver",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "orderId",
        type: "string",
      },
    ],
    name: "EventConfirmReceipt",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "orderId",
        type: "string",
      },
    ],
    name: "EventCreateOrder",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "EventDepositSecurity",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "EventWithdraw",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "EventwithdrawSecurity",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "DOMAIN_SEPARATOR",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "EIP712DOMAIN_TYPEHASH",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "USDC_ADDRESS",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "USDT_ADDRESS",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "wallet", type: "address" }],
    name: "accounts",
    outputs: [
      { internalType: "uint256", name: "balance", type: "uint256" },
      { internalType: "uint256", name: "frozenBalance", type: "uint256" },
      { internalType: "uint256", name: "securityDeposit", type: "uint256" },
      {
        internalType: "uint256",
        name: "frozenSecurityDeposit",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "admin",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "id", type: "string" }],
    name: "cancelOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "id", type: "string" },
      { internalType: "bytes", name: "signature", type: "bytes" },
    ],
    name: "confirmDeliver",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "id", type: "string" },
      { internalType: "bytes", name: "signature", type: "bytes" },
    ],
    name: "confirmReceipt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "id", type: "string" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "address", name: "buyer", type: "address" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "uint256", name: "quantity", type: "uint256" },
          { internalType: "uint256", name: "feesRatio", type: "uint256" },
          { internalType: "uint256", name: "securityDeposit", type: "uint256" },
          {
            internalType: "uint256",
            name: "fundReleasePeriod",
            type: "uint256",
          },
        ],
        internalType: "struct LibraContract.OrderParams",
        name: "orderInfo",
        type: "tuple",
      },
      { internalType: "bytes", name: "signature", type: "bytes" },
    ],
    name: "createOrder",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "depositSecurity",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "wallet", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "freezeOrderIds",
    outputs: [{ internalType: "string", name: "orderIds", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "accountAddress", type: "address" },
    ],
    name: "getAccount",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "balance", type: "uint256" },
          { internalType: "uint256", name: "frozenBalance", type: "uint256" },
          { internalType: "uint256", name: "securityDeposit", type: "uint256" },
          {
            internalType: "uint256",
            name: "frozenSecurityDeposit",
            type: "uint256",
          },
        ],
        internalType: "struct LibraContract.Account",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "id", type: "string" }],
    name: "getOrder",
    outputs: [
      {
        components: [
          { internalType: "string", name: "id", type: "string" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "address", name: "buyer", type: "address" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "uint256", name: "payTime", type: "uint256" },
          { internalType: "uint256", name: "quantity", type: "uint256" },
          { internalType: "uint256", name: "feesRatio", type: "uint256" },
          { internalType: "uint256", name: "completeTime", type: "uint256" },
          { internalType: "uint256", name: "securityDeposit", type: "uint256" },
          {
            internalType: "uint256",
            name: "fundReleasePeriod",
            type: "uint256",
          },
          {
            internalType: "enum LibraContract.OrderStatus",
            name: "state",
            type: "uint8",
          },
        ],
        internalType: "struct LibraContract.Order",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "id", type: "string" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "address", name: "buyer", type: "address" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "uint256", name: "quantity", type: "uint256" },
          { internalType: "uint256", name: "feesRatio", type: "uint256" },
          { internalType: "uint256", name: "securityDeposit", type: "uint256" },
          {
            internalType: "uint256",
            name: "fundReleasePeriod",
            type: "uint256",
          },
        ],
        internalType: "struct LibraContract.OrderParams",
        name: "orderInfo",
        type: "tuple",
      },
    ],
    name: "getStructHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "id", type: "string" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "address", name: "buyer", type: "address" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "uint256", name: "quantity", type: "uint256" },
          { internalType: "uint256", name: "feesRatio", type: "uint256" },
          { internalType: "uint256", name: "securityDeposit", type: "uint256" },
          {
            internalType: "uint256",
            name: "fundReleasePeriod",
            type: "uint256",
          },
        ],
        internalType: "struct LibraContract.OrderParams",
        name: "orderInfo",
        type: "tuple",
      },
    ],
    name: "getTypedDataHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "orderId", type: "string" }],
    name: "orders",
    outputs: [
      { internalType: "string", name: "id", type: "string" },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "address", name: "buyer", type: "address" },
      { internalType: "address", name: "seller", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "payTime", type: "uint256" },
      { internalType: "uint256", name: "quantity", type: "uint256" },
      { internalType: "uint256", name: "feesRatio", type: "uint256" },
      { internalType: "uint256", name: "completeTime", type: "uint256" },
      { internalType: "uint256", name: "securityDeposit", type: "uint256" },
      { internalType: "uint256", name: "fundReleasePeriod", type: "uint256" },
      {
        internalType: "enum LibraContract.OrderStatus",
        name: "state",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "seller", type: "address" }],
    name: "releaseFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_signer", type: "address" }],
    name: "setSigner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "signer",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "id", type: "string" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "address", name: "buyer", type: "address" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "uint256", name: "quantity", type: "uint256" },
          { internalType: "uint256", name: "feesRatio", type: "uint256" },
          { internalType: "uint256", name: "securityDeposit", type: "uint256" },
          {
            internalType: "uint256",
            name: "fundReleasePeriod",
            type: "uint256",
          },
        ],
        internalType: "struct LibraContract.OrderParams",
        name: "orderInfo",
        type: "tuple",
      },
      { internalType: "uint8", name: "v", type: "uint8" },
      { internalType: "bytes32", name: "r", type: "bytes32" },
      { internalType: "bytes32", name: "s", type: "bytes32" },
    ],
    name: "verify",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "withdrawSecurity",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
]
